 USE productsDB;
CREATE TABLE Users(
UserID VARCHAR(255) PRIMARY KEY,
UserName VARCHAR(255) NOT NULL,
Email VARCHAR(255) NOT NULL UNIQUE,
UserPassword VARCHAR (255) NOT NULL,
IsDeleted INT DEFAULT 0,
IsEmailSent INT DEFAULT 0


)